config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'users/list'
  get 'home/index'
  devise_for :users
  get 'tests/index'
  # get 'questions/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  patch  'setStatus'  => 'questions#setStatus'
  post  'create_test' => 'tests#create_test'
  get   'do_test' => 'tests#do_test'
  # put 'do_test' => 'tests#save_test'
  # patch 'do_test' => 'tests#save_test'
  patch  'setRole'  => 'users#setRole'

  get 'all_question' => 'questions#all_question'
  get 'enable_question' => 'questions#enable_question'
  get 'disable_question' => 'questions#disable_question'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root 'home#index'
  resources :questions
  resources :tests
  resources :users
end

app/models/question.rb
class Question < ApplicationRecord
	validates :content, presence: true,
					length: { minimum: 5, maximun: 1000 }
	validates :answer1, :answer2, :answer3, :answer4, presence: true,
					length: { minimum: 1, maximum: 100 }
	validates_with CheckboxValidator
	validate :image_validation, :video_validation, :sound_validation
	
	has_one_attached :image
	has_one_attached :video
	has_one_attached :sound

	def image_validation
		if image.attached?  
			if !image.blob.content_type.starts_with?('image/')
				image.purge
				errors[:base] << 'Attach file is not image'
			elsif image.blob.byte_size > 5242880
				image.purge
				errors[:base] << 'image must be less than 5 MB'
			end
		end
	end

	def video_validation
		if video.attached?  
			if !video.blob.content_type.starts_with?('video/')
				video.purge
				errors[:base] << 'Attach file is not video'
			elsif video.blob.byte_size > 104857600
				video.purge
				errors[:base] << 'video must be less than 100 MB'
			end
		end
	end

	def sound_validation
		if sound.attached?  
			if !sound.blob.content_type.starts_with?('audio/')
				sound.purge
				errors[:base] << 'Attach file is not audio'
			elsif sound.blob.byte_size > 10485760
				sound.purge
				errors[:base] << 'audio must be less than 10 MB'
			end
		end
	end

	def self.search(content_search, status)
		case status
		when 'all'
			if content_search
				where(['content LIKE ?', "%#{content_search}%"])
			else
				all
			end
		when 'enable'
			if content_search
				where(['content LIKE ? AND disable = ?', "%#{content_search}%", false])
			else
				where(['disable = ?', false])
			end
		when 'disable'
			if content_search
				where(['content LIKE ? AND disable = ?', "%#{content_search}%", true])
			else
				where(['disable = ?', true])
			end
		else
			all
		end
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :only_admin

  def index
    @questions = Question.search(params[:content_search], params[:status_search]).paginate(page: params[:page], per_page: 6)
    # @questions = Question.all
    session[:all] = params[:status_search]
    @total_number_of_question = Question.count
    @number_of_enable_question = Question.count {|question| question.disable == false}
    @number_of_disable_question = Question.count {|question| question.disable == true}
  end
 

  
  def all_question
    @questions = Question.all
    session[:all] = 'all'
    respond_to do |format|
      format.html {redirect_to questions_path}
      format.js {}
    end
  end

  def enable_question
    @questions = Question.select {|question| question.disable == false}
    session[:all] = 'enable'
    respond_to do |format|
      format.html {redirect_to questions_path}
      format.js {}
    end
  end

  def disable_question
    @questions = Question.select {|question| question.disable == true}
    session[:all] = 'disable'
    respond_to do |format|
      format.html {redirect_to questions_path}
      format.js {}
    end
  end

  def new
    @question = Question.new
    @question.attach_type = "No attach"
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(question_params)
    @question.disable = false
    
    case @question.attach_type
    when "Images"
      @question.image.attach(params[:question][:image])
    when "Sound"
      @question.sound.attach(params[:question][:sound])
    when "Video"
      @question.video.attach(params[:question][:video])
    end
    
    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def update
    @question = Question.find(params[:id])
    @question.update(disable: true)

    @new_question = Question.new(question_params)
    @new_question.disable = false

    case @new_question.attach_type
    when "Images"
      @new_question.image.attach(params[:question][:image])
    when "Sound"
      @new_question.sound.attach(params[:question][:sound])
    when "Video"
      @new_question.video.attach(params[:question][:video])
    end

    if @new_question.save
      redirect_to @new_question
    else
      render 'edit'
    end
  end

  def setStatus
    @question = Question.find(params[:id])
    if @question.disable == true
      @question.update(disable: false)
      @status = 'Công khai'
      @b = 'Disable'
    else
      @question.update(disable: true)
      @status = 'Vô hiệu hóa'
      @b = 'Enable'
    end

    @number_of_enable_question = Question.count {|question| question.disable == false}
    @number_of_disable_question = Question.count {|question| question.disable == true}

    respond_to do |format|
      format.html {redirect_to questions_path}
      format.js {}
    end
  end

  def question_params
    params.require(:question).permit(:content, :attach_type, :answer1, :answer2, 
      :answer3, :answer4, :correct1, :correct2, :correct3, :correct4)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_image_field.html.erb
<fieldset>
    <div class = "image-preview">
        <img />
    </div>
    <%= f.file_field :attach_file, class:'file', accept:"image/*" %>
</fieldset>

<!-- script for image upload -->
<script> 
$('document').ready(function(){
    var preview = $(".image-preview img");
    $(".file").change(function(event){
       var input = $(event.currentTarget);
       var file = input[0].files[0];
       var reader = new FileReader();
       reader.onload = function(e){
           image_base64 = e.target.result;
           preview.attr("src", image_base64);
       };
       reader.readAsDataURL(file);
    });
});
</script>

app/views/questions/_question.html.erb
<tr>
	<td><%= question.content %></td>
	<td>
		<% if question.attach_type == "No attach" %>
			<i class="fa fa-ban" style="font-size:20px"></i> None
		<% elsif question.attach_type == "Video" %>
			<i class="fa fa-file-video-o" style="font-size:20px"></i> Video
		<% elsif question.attach_type == "Sound"%>
			<i class="fa fa-file-audio-o" style="font-size:20px"></i> Mp3
		<% else %>
			<i class="fa fa-file-image-o" style="font-size:20px"></i> Image
		<% end %>
	</td>
	<td>	
	<% if question.disable == true %>
		<span id = '<%='show-status-'+question.id.to_s%>'>Vô hiệu hóa</span>
		<% b = 'Enable'%>
	<% else %>
		<span id = '<%='show-status-'+question.id.to_s%>'>Công khai</span>
		<% b = 'Disable' %>
	<% end %>
	</td>
	<td><%= question.updated_at %></td>
	<td>
		<%= link_to b, setStatus_path(id: question.id), method: :patch, data: { confirm: 'Are you sure?' }, 
			remote: true, class: "set-status-question", id: 'button-status-'+question.id.to_s %>
		<%= link_to 'Show', question_path(question) %>
		<%= link_to 'Edit', edit_question_path(question) %>
	</td>
</tr>

app/views/questions/_question_form.html.erb
<div class="card-body">
  <h2 class="title">Phần câu hỏi</h2>
  <%= form_for @question do |form| %>
    <!--<% if @question.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@question.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @question.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>-->
    <div class="row row-space">
      <div class="col-9">
        <div class="input-group">
          <label class="label">Nội dung câu hỏi</label>
          <%= form.text_field :attach_type ,hidden: true ,value: @question.attach_type ,id: "attach_type"%>
          <%= form.text_area :content ,class:"input--style-4 form-control" ,id: "ques_content",
            placeholder: "Nội dung" ,minlength:"5" ,maxlength: "1000" ,required: true ,onkeyup: "auto_grow(this)"%>
          <div class="invalid-feedback">
              Vui lòng nhập nội dung câu hỏi.
          </div>
        </div>
        
				
        <% case @question.attach_type %>
				<% when "Images" %>
					<div class="image-preview d-flex justify-content-center p-3"><%=image_tag @question.image %></div>
          <video controls autoplay id="video_player" class="display_none"></video>
          <audio controls id="audio_player" class="display_none"></audio>
				<% when "Sound" %>
          <div class="image-preview"><img/></div>
          <video controls autoplay id="video_player" class="display_none"></video>
					<%= audio_tag rails_blob_path(@question.sound), controls: true ,id:"audio_player"%>
				<% when "Video" %>
          <div class="image-preview d-flex justify-content-center p-3"><img/></div>
					<%= video_tag rails_blob_path(@question.video), controls: true ,id:"video_player" %>
          <audio controls id="audio_player" class="display_none"></audio>
				<% when "No attach" %>
          <div class="image-preview d-flex justify-content-center p-3"><img/></div>
          <video controls autoplay id="video_player" class="display_none"></video>
          <audio controls id="audio_player" class="display_none"></audio>
        <% end %>
      </div>
      <div class="col-3">
        <label class="label">&nbsp;</label>
        <div class="btn-group" role="group">
          <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" 
          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Trắc nghiệm
          </button>
        </div>
      </div>
    </div>
    <div class="row row-space mt-2">
      <div class="col-7">
        <label class="label--inline">Đính kèm</label>
        <div class="btn-group pl-2" role="group">
          <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle"
           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="selection">Không</span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
            <li class="dropdown-item" value="0">
              <div  class="custom-file-upload" >
                <i class="fa fa-ban" style="font-size: 25px;"></i> 
                Không
              </div>
            </li>
            <li class="dropdown-item" value="1">
              <label for="image-upload" class="custom-file-upload" id="image-upload-label">
                <i class="fa fa-picture-o" style="font-size: 25px;"></i> 
                Hình ảnh
              </label>
            </li>
            <li class="dropdown-item" value="2">
              <label for="audio-upload" class="custom-file-upload" id="audio-upload-label">
                <i class="fa fa-file-audio-o" style="font-size: 25px;"></i>
                Audio ngắn
              </label>
            </li>
            <li class="dropdown-item" value="3">
              <label for="video-upload" class="custom-file-upload" id="video-upload-label">
                <i class="fa fa-file-video-o" style="font-size: 25px;"></i>
                Video ngắn
              </label>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-5">
        <div class="input-group">
          <%= form.file_field :image, class:'file--ques', accept:"image/*" ,id:"image-upload"%>
        </div>
        <div class="input-group">
          <%= form.file_field :video, class:'file--ques', accept:"video/*" ,id:"video-upload"%>
        </div>
        <div class="input-group">
          <%= form.file_field :sound, class:'file--ques', accept:"audio/*" ,id:"audio-upload"%>
        </div>
      </div>
    </div>
    <h2 class="title pt-4 mt-3">Phần câu trả lời</h2>
    <div class="row row-space">
      <div class="col-2">
        <label class="label">Đúng</label>
      </div>
      <div class="col-10">
        <label class="label">Nội dung</label>
      </div>
    </div>
    <div class="row row-space  pt-2">
      <div class="col-1 pt-2">
        <%= form.check_box :correct1 ,class:"form-check-input css-checkbox" ,id:"correct1_check"%>
        <label for="correct1_check" class="css-label"></label>
      </div>
      <div class="col-11">
        <%= form.text_field :answer1 ,class:"input--style-4 form-control" , placeholder:"Đáp án thứ nhất" ,required: true ,maxlength: "100"%>
      </div>
    </div>
    <div class="row row-space  pt-2">
      <div class="col-1 pt-2">
        <%= form.check_box :correct2 ,class:"form-check-input css-checkbox" ,id:"correct2_check" %>
        <label for="correct2_check" class="css-label"></label>
      </div>
      <div class="col-11">
        <%= form.text_field :answer2 ,class:"input--style-4 form-control" , placeholder:"Đáp án thứ hai" ,required: true ,maxlength: "100"%>
      </div>
    </div>
    <div class="row row-space  pt-2">
      <div class="col-1 pt-2">
        <%= form.check_box :correct3 ,class:"form-check-input css-checkbox" ,id:"correct3_check" %>
        <label for="correct3_check" class="css-label"></label>
      </div>
      <div class="col-11">
        <%= form.text_field :answer3 ,class:"input--style-4 form-control" , placeholder:"Đáp án thứ ba" ,required: true ,maxlength: "100"%>
      </div>
    </div>
    <div class="row row-space  pt-2">
      <div class="col-1 pt-2">
        <%= form.check_box :correct4 ,class:"form-check-input css-checkbox" ,id:"correct4_check"%>
        <label for="correct4_check" class="css-label"></label>
      </div>
      <div class="col-11">
        <%= form.text_field :answer4 ,class:"input--style-4 form-control" , placeholder:"Đáp án thứ tư" ,required: true ,maxlength: "100"%>
      </div>

    </div>
    <% if @question.errors.messages[:base].any? %>
    <div class="row row-space  pt-2">
      <div class="col-1"></div>
      <div class="invalid-feedback display-inline col-11" >
        Vui lòng chọn đáp án đúng !
      </div>
      <div class="invalid-feedback display-inline col-11" id="invalid-file">
        Vui lòng chọn đáp án đúng !
      </div>
    </div>
    <% end %>
    <div class="row row-space  pt-2">
      <div class="col-1"></div>
      <div class="invalid-feedback display-inline col-11" id="invalid-file" 
      style="visibility: visible;"></div>
    </div>
    <div class="row row-space  pt-4">
      <% if action_name == 'edit' %>
        <%= form.submit "UPDATE CÂU HỎI", class: "btn btn-warning", id:"submit-question-btn"%>
      <% else %>
        <%= form.submit "TẠO CÂU HỎI", class: "btn btn-warning", id:"submit-question-btn"%>
      <% end %>
    </div>
  <% end %>
</div>

app/views/questions/all_question.js.erb
$('#show-question').html("<%= j render @questions %>");

app/views/questions/disable_question.html.erb
$('#show-question').html("<%= j render @questions %>");

app/views/questions/edit.html.erb
<% if @question.disable == true %>
    <% b = '<input type="checkbox" data-toggle="toggle" data-on="Enabled" data-off="Disabled" checked>'%>
<% else %>
    <% b = '<input type="checkbox" data-toggle="toggle" data-on="Enabled" data-off="Disabled">' %>
<% end %>

<div class="page-wrapper bg-gra-02 p-b-100 font-poppins">
  <div class="wrapper wrapper--w680 pt-3 pb-4">
    <div class="card card-4">
      <div class="card-header d-flex">
        <h4 class="mr-auto">Chỉnh sửa câu hỏi</h4>
    
            <%= link_to b.html_safe, setStatus_path(id: @question.id), method: :patch, 
    data: { confirm: 'Are you sure?' }, remote: true, class: "set-status-question", 
    id: 'button-status-' + @question.id.to_s %>
      </div>
      <%= render 'question_form' %>
    </div>
  </div>
</div>

<script type="text/javascript">
  display_frame();
</script>

app/views/questions/enable_question.js.erb
$('#show-question').html("<%= j render @questions %>");

app/views/questions/index.html.erb
<div class="main-container container-fluid main-content pt-4">
	<section class="section home-section sevice-section text-white no-padding no-margin" id="service">
		<div class="row no-margin">
			<div class="col-md-2 left-container">
				<div class="d-flex justify-content-center  mb-3">
					<%= link_to '<i class="fa fa-pencil-square-o" style="font-size:24px"></i> Thêm câu hỏi'.html_safe,
					 new_question_path ,class:"btn btn-warning"%>
				</div>
				<ul class="list-group email-action">
					<li class="list-group-item d-flex justify-content-between align-items-center list-group-item-action active-li-item">
						<%= link_to '<i class="fa fa-book" style="font-size:20px"></i> Tất cả'.html_safe,
						 questions_path(status_search: "all"), method: :get, remote: true %>
						<span class="badge badge-primary badge-pill"><%= @total_number_of_question %></span>
					</li>
					<li class="list-group-item d-flex justify-content-between align-items-center list-group-item-action">
						<%= link_to '<i class="fa fa-globe" style="font-size:20px"></i> Công khai'.html_safe, 
						questions_path(status_search: "enable"), method: :get, remote: true %>
						<span class="badge badge-primary badge-pill" id = "numer-enable-question"><%= @number_of_enable_question %></span>
					</li>
					<li class="list-group-item d-flex justify-content-between align-items-center list-group-item-action">
						<%= link_to '<i class="fa fa-lock" style="font-size:20px" aria-hidden="true"></i> Vô hiệu hóa'.html_safe,
						 questions_path(status_search: "disable"), method: :get, remote: true %>
						<span class="badge badge-primary badge-pill" id = "numer-disable-question"><%= @number_of_disable_question %></span>
					</li>
				</ul>
			</div>
			<div class="col-md-10 right-container">
				<div class="card">
					<div class="card-header">
						<div class="row">
							<div class="col-sm-6">
								<h2 id="title-page">Bảng câu hỏi</h2>
							</div>
								<div class="col-sm-6 ">
									<div class="input-group">
										<%= form_tag questions_path, method: :get, remote: true, id: 'question-search', class:"form-inline my-2 my-lg-0"  do %>
    										<%= text_field_tag :content_search, params[:content_search], class:"form-control", placeholder:"Nội dung tìm kiếm .." %>
    										<%= select_tag :status_search, options_for_select([['all', 'all'], ['enable', 'enable'], ['disable', 'disable']], params[:status_search]) %>
											<div class="input-group-append">
												<%= submit_tag "Search", name: nil, class:"btn btn-outline-secondary" %>
											</div>    											
										<% end %>
									</div> 
								</div>	
								<!--<div class="col-sm-6 ">
										<div class="input-group">											
											<input type="text" class="form-control" placeholder="Nội dung tìm kiếm .." aria-label="Search for">
											<div class="input-group-append">
												<button class="btn btn-outline-secondary" type="button">Tìm kiếm</button>
											</div>
										</div> 
								</div>-->
						</div>
					</div>
					<div class="card-body">
						<div id="all-mail" >
							<table class="table table-hover table-bordered mail-table">
								<thead class="thead-dark">
									<tr> 
										<th scope="col">Nội dung</th>
										<th scope="col">Đính kèm</th>
										<th scope="col">Tình trạng</th>
										<th scope="col">Edit lần cuối</th>
										<th scope="col">Chỉnh sửa</th>
									</tr>
								</thead>
								<tbody id="show-question">
									<%= render @questions %>
								</tbody>
							</table>
							<!--<div class="clearfix">
								<div class="hint-text white_color">Showing <b>5</b> out of <b>25</b> entries</div>
								<ul class="pagination">
									<li class="page-item"><a href="#"  class="page-link">Previous</a></li>
									<li class="page-item"><a href="#" class="page-link">1</a></li>
									<li class="page-item"><a href="#" class="page-link">2</a></li>
									<li class="page-item active"><a href="#" class="page-link">3</a></li>
									<li class="page-item"><a href="#" class="page-link">4</a></li>
									<li class="page-item"><a href="#" class="page-link">5</a></li>
									<li class="page-item"><a href="#" class="page-link">Next</a></li>
								</ul>
							</div>-->
						<div id="show_will_paginate"><%= will_paginate @questions %></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>

app/views/questions/index.js.erb
$("#show-question").html("<%= escape_javascript(render @questions) %>");
$("#show_will_paginate").html("<%= escape_javascript(will_paginate @questions) %>");

app/views/questions/new.html.erb
<div class="page-wrapper bg-gra-02 p-b-100 font-poppins">
  <div class="wrapper wrapper--w680 pt-3 pb-4">
    <div class="card card-4">
      <div class="card-header">
        <%# <%= link_to 'Back', questions_path, class:"btn btn-secondary btn-sm", role:"button", style: "margin-top:10px;" %>
        <h4>Tạo câu hỏi mới</h4>
      </div>
      <%= render 'question_form' %>
    </div>
  </div>
</div>

app/views/questions/setStatus.js.erb
$('#<%='show-status-'+@question.id.to_s%>').html("<%= @status %>");
$('#<%='button-status-'+@question.id.to_s%>').text('<%= @b%>');
$('#numer-enable-question').html('<%= @number_of_enable_question %>');
$('#numer-disable-question').html('<%= @number_of_disable_question %>')
if (<%= session[:all] == 'enable' || session[:all] == 'disable' %>){
    $('#<%='button-status-'+@question.id.to_s%>').bind('ajax:success', function() {$(this).closest('tr').fadeOut();});
}

app/views/questions/show.html.erb
<div class="container mt-4">
	<div class="card">
	  <div class="card-body">
      <%# <%= link_to 'Back', questions_path, class:"btn btn-secondary btn-sm", role:"button", style: "margin-top:10px;" %>
			<div class="d-flex">
				<div class="mr-auto p-2">
					<h2 id="title-page">Câu hỏi vừa khởi tạo</h2>
				</div>
				<div class="p-2">
					<p><strong>Trạng thái : </strong>
					<% if @question.disable == true %>
						<% b = 'Vô hiệu hóa'%>
					<% else %>
						<% b = 'Công khai' %>
					<% end %> 
					</p>
					<p><strong>Thời gian khởi tạo : </strong><%= @question.created_at %></p>
					<%= link_to 'Edit', edit_question_path(@question) %>
				</div>
			</div>
		  <hr>
		  <div class="question-block mt-3"> 
		  	<p class="question-title">
					<strong>Câu hỏi : </strong>
					<%= @question.content %>
				</p>
				<% case @question.attach_type %>
				<% when "Images" %>
				<div class="d-flex justify-content-center pb-3">	<%= image_tag @question.image ,class:"ques-test-img"%> </div>
				<% when "Sound" %>
					<%= audio_tag rails_blob_path(@question.sound), controls: true %>
				<% when "Video" %>
					<%= video_tag rails_blob_path(@question.video), controls: true %>
				<% end %>
 				<div class="answer-block" data-question-type="multi_choice">
 					<div class="question-form" accept-charset="UTF-8" method="post"> 

            <%if @question.correct1 %>
              <div class="s_question_selection checked_border right_checked_border d-flex">
                <span class="choice-index-span">
                  <code><%= @question.answer1 %></code>
                </span>
              </div>
            <% else %>
              <div class="s_question_selection checked_border">
                <span class="choice-index-span">
                  <code><%= @question.answer1 %></code>
                </span>
              </div>
            <% end %>

						<%if @question.correct2 %>
              <div class="s_question_selection checked_border right_checked_border d-flex">
                <span class="choice-index-span">
                  <code><%= @question.answer2 %></code>
                </span>
              </div>
            <% else %>
              <div class="s_question_selection checked_border">
                <span class="choice-index-span">
                  <code><%= @question.answer2 %></code>
                </span>
              </div>
            <% end %>
						            
						<%if @question.correct3 %>
              <div class="s_question_selection checked_border right_checked_border d-flex">
                <span class="choice-index-span">
                  <code><%= @question.answer3 %></code>
                </span>
              </div>
            <% else %>
              <div class="s_question_selection checked_border">
                <span class="choice-index-span">
                  <code><%= @question.answer3 %></code>
                </span>
              </div>
            <% end %>
						            
						<%if @question.correct4 %>
              <div class="s_question_selection checked_border right_checked_border d-flex">
                <span class="choice-index-span">
                  <code><%= @question.answer4 %></code>
                </span>
              </div>
            <% else %>
              <div class="s_question_selection checked_border">
                <span class="choice-index-span">
                  <code><%= @question.answer4 %></code>
                </span>
              </div>
            <% end %>

 					</div>
 				</div>
 			</div>
			<hr>
			<div class="d-flex justify-content-center">

			</div>
	  </div>
	</div>
</div>