config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'users/list'
  get 'home/index'
  devise_for :users
  get 'tests/index'
  # get 'questions/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  patch  'setStatus'  => 'questions#setStatus'
  post  'create_test' => 'tests#create_test'
  get   'do_test' => 'tests#do_test'
  # put 'do_test' => 'tests#save_test'
  # patch 'do_test' => 'tests#save_test'
  patch  'setRole'  => 'users#setRole'

  get 'all_question' => 'questions#all_question'
  get 'enable_question' => 'questions#enable_question'
  get 'disable_question' => 'questions#disable_question'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root 'home#index'
  resources :questions
  resources :tests
  resources :users
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user.role == 'user'
      @tests = current_user.tests.all.paginate(page: params[:page], per_page: 6)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_admin_index.html.erb
<p>
    <%= link_to 'Question', questions_path %>
</p>

<p>
    <%= link_to 'Tests', tests_path%>
</p>

<p>
    <%= link_to 'List all accounts', users_list_path %>
</p>

app/views/home/_user_index.html.erb
<div class="pt-4 d-flex justify-content-center">
	<div class="card card_center">
		<div class="card-header">
			<div class="row">
				<div class="col-sm-6">
					<h2 id="title-page">Tổng hợp bài test</h2>
				</div>
			</div>
		</div>
		<div class="card-body">
			<%= button_to 'Làm bài test', create_test_path, data: { confirm: 'Are you sure?' },
			 	method: :post, remote: true, class: "do-test btn btn-outline-warning mb-3" %> 
			<div id="all-mail" >
				<table class="table table-hover table-bordered mail-table">
					<thead class="thead-dark">
						<tr> 
							<th scope="col">STT</th>
							<th scope="col">Điểm số</th>
							<th scope="col">Trạng thái</th>
							<th scope="col">Thời gian tạo</th>
							<th scope="col"></th>
						</tr>
					</thead>
					<tbody>
						<% @tests.each_with_index do |test ,index| %>
							<% if test.is_submit == false %>
							<tr class="not_submit_tr">
							<% else %>
							<tr>
							<% end %>
								<td><%= index + 1 %></td>
								<td><%= test.score  %></td>
								<td>
									<% if test.is_submit == true %>
										<%= 'Đã hoàn thành' %>
									<% else %>
										<%= 'Chưa hoàn thành' %> 
									<% end %>  
								</td>
								<td><%= test.created_at  %></td>
								<td>
									<% if test.is_submit == false %>
										<%= link_to 'Tiếp tục hoàn thành', do_test_path(id: test.id) %>
									<% else %>
										<%= link_to 'Xem', test_path(test)%>
									<% end %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
				<div id="show_will_paginate"><%= will_paginate @tests %></div>
			</div>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<% if current_user.role == 'admin' %>
    <% controller.redirect_to questions_path %>
<% else %>
    <%= render 'user_index' %>
<% end %>