config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'users/list'
  get 'home/index'
  devise_for :users
  get 'tests/index'
  # get 'questions/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  patch  'setStatus'  => 'questions#setStatus'
  post  'create_test' => 'tests#create_test'
  get   'do_test' => 'tests#do_test'
  # put 'do_test' => 'tests#save_test'
  # patch 'do_test' => 'tests#save_test'
  patch  'setRole'  => 'users#setRole'

  get 'all_question' => 'questions#all_question'
  get 'enable_question' => 'questions#enable_question'
  get 'disable_question' => 'questions#disable_question'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  root 'home#index'
  resources :questions
  resources :tests
  resources :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoQuiz</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  
  <%# <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' % >
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' % > %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
  <% if current_user == nil or current_user.role == 'user' %>
	<nav class="navbar navbar-expand-lg navbar-dark">
	  <a class="navbar-brand" href="#">
    <%= fa_stacked_icon "question-circle"%>QUESTIONS</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
	    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
	      <li class="nav-item active">
          <%= link_to 'TRANG CHỦ', root_path, class:"nav-link" ,id:"home_link"%>
	      </li>
	    </ul>
	    <form class="form-inline my-2 my-lg-0 nav_user">
        <% if user_signed_in? %>
          <span>Hello <%= current_user.email %></span>
          <a href= "<%= edit_user_registration_path(current_user)%>" class ="pl-3">
            <i class='fa fa-user nav_icon'></i> Edit profile
          </a>
          <a href="<%= destroy_user_session_path%>" data-method="delete" class ="pl-3">
            <i class="fa fa-sign-out nav_icon"></i> Logout
          </a>
        <% else %>
          <a href='<%= new_user_session_path%>' class ="pl-3">
            <i class='fa fa-sign-in nav_icon'></i> Login
          </a>
          <a href='<%= new_user_registration_path%>' class ="pl-3">
            <i class="fa fa-pencil-square-o nav_icon"></i> Sign up
          </a>           
        <% end %>
	      
	    </form>
	  </div>
	</nav>

  <% elsif current_user.role == 'admin' %>
	<nav class="navbar navbar-expand-lg navbar-dark">
	  <a class="navbar-brand" href="#">
    <%= fa_stacked_icon "question-circle"%>ADMIN</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
	    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
	      <li class="nav-item">
          <%= link_to 'CÂU HỎI', questions_path, class:"nav-link" ,id:"home_link"%>
	      </li>
	      <li class="nav-item">
          <%= link_to 'BÀI TEST', tests_path, class:"nav-link" ,id:"test_link"%>
	      </li>
	      <li class="nav-item">
          <%= link_to 'TÀI KHOẢN', users_path, class:"nav-link" ,id:"user_link"%>
	      </li>
	    </ul>
	    <form class="form-inline my-2 my-lg-0 nav_user">
        <% if user_signed_in? %>
          <span>Hello <%= current_user.email %></span>
          <a href= "<%= edit_user_registration_path(current_user)%>" class ="pl-3">
            <i class='fa fa-user nav_icon'></i> Edit profile
          </a>
          <a href="<%= destroy_user_session_path%>" data-method="delete" class ="pl-3">
            <i class="fa fa-sign-out nav_icon"></i> Logout
          </a>
        <% else %>
          <a href='<%= new_user_session_path%>' class ="pl-3">
            <i class='fa fa-sign-in nav_icon'></i> Login
          </a>
          <a href='<%= new_user_registration_path%>' class ="pl-3">
            <i class="fas fa-user-plus nav_icon"></i> Sign up
          </a>           
        <% end %>
	      
	    </form>
	  </div>
	</nav>
  <% end %>

  <% if controller_name != "sessions" and controller_name != "home"%>
  <div class="container">
    <section class="content" style="min-height: auto;">
      <% flash.each do |key, value| %>
        <div class="row">
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        </div>
      <% end %>
    </section>
  </div>
  <% end %>

  <!--Main content-->
  <%= yield %>

  <!--Footer-->
  <!--
  <footer class="container footer">
    <nav class="navbar d-flex">
      <ul>
        <li>Make by: Benni & Charlie</li>
      </ul>
      <p> © 2019 QUESTION </p>
    </nav>
  </footer>-->
  
</body>
</html>